name: PEACEMAKER-CYBER 
services:
  - name: PEACEMAKER-CYBER-SERVICE
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
